# ---------------------------------------------------------------
# 方案设置
# ---------------------------------------------------------------

scheme: Gemini

# ---------------------------------------------------------------
# 站点信息设置
# ---------------------------------------------------------------

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

# ---------------------------------------------------------------
# 菜单设置
# ---------------------------------------------------------------

menu:
  开始使用: /starting/ || far fa-cog
  基本用法: /using/ || far fa-anchor
  样式详解:
    default: /styling/ || far fa-palette
    堆叠: /stacking/ || far fa-box
    变形: /transforms/ || far fa-brush
    遮罩: /masking/ || far fa-cannabis
    分层: /layering/ || far fa-cat
    双色: /duotone/ || far fa-adjust
  图标列表:
    default: /icons/ || far fa-icons
    Solid: /solid/
    Regular: /regular/
    Light: /light/
    Duotone: /duotone/
    Brands: /brands/
  天气主题: /weather/ || far fa-cloud

# ---------------------------------------------------------------
# 侧边栏设置
# 参见：https://mopsite.github.io/next/theme-settings/sidebar/
# ---------------------------------------------------------------

# 侧边栏头像
avatar:
  # 设置链接以替换默认图像
  url: /images/avatar.svg
  # 如果为 true，头像将显示为圆形
  rounded: true

# 侧边栏显示文章 / 分类 / 标签
site_state: false

# 侧边栏链接管理
links_settings:
  icon:
  title:
  # 链接布局，可用值：block | inline
  layout: block

links:
  Git: https://mopsite.github.io/git
  Hexo: https://mopsite.github.io/hexo
  NexT: https://mopsite.github.io/next

# ---------------------------------------------------------------
# 页脚设置
# 参见：https://mopsite.github.io/next/theme-settings/footer/
# ---------------------------------------------------------------

footer:
  # 建站年份，如果不设置，则只显示当前年份
  since: 2021

  # 年份和版权之间的图标
  icon:
    # 如果想要动画图标，设置为true
    animated: true

  # 是否显示强力驱动
  powered: false

# ---------------------------------------------------------------
# 其他设置
# 参见：https://mopsite.github.io/next/theme-settings/miscellaneous/
# ---------------------------------------------------------------

codeblock:
  # 代码块高亮主题
  # 所有可用的主题：https://theme-next.js.org/highlight/
  theme:
    light: agate
    dark: agate
  # 代码块复制按钮
  copy_button:
    enable: true
    # 可用值：default | flat | mac
    style: mac

back2top:
  # 返回顶部按钮中显示滚动百分比
  scrollpercent: true

# 阅读进度条
reading_progress:
  enable: true
  # 可用值：top | bottom
  position: bottom

# ---------------------------------------------------------------
# 第三方插件和服务设置
# 参见：https://mopsite.github.io/next/third-party-services/
# 更多插件：https://github.com/next-theme/awesome-next
# 你可能需要安装相应的依赖包
# ---------------------------------------------------------------

# 为你的网站提供快速浏览
# 更多信息：https://github.com/next-theme/pjax
pjax: true

# FancyBox 是一款用来缩放图片的工具
# 更多信息：https://fancyapps.com/fancybox/
fancybox: true

# 盘古之白，用于在中英文之间自动插入空格
# 更多信息：https://github.com/vinta/pangu.js
pangu: true

# 快速链接
# 更多信息：https://getquick.link
quicklink:
  enable: true

# ---------------------------------------------------------------
# 搜索服务
# ---------------------------------------------------------------

# 本地搜索
# 依赖包：https://github.com/next-theme/hexo-generator-searchdb
# 参见：https://mopsite.github.io/next/third-party-services/local-search/

local_search:
  enable: true

# ---------------------------------------------------------------
# 标签插件设置
# 参见：https://mopsite.github.io/next/tag-plugins/
# ---------------------------------------------------------------

# 便签标签
note:
  # 便签标签样式值
  style: flat
  icons: false

# PDF 标签
# NexT 会默认加载 pdf 文件，如果加载失败，会启用 pdf.js。
# 如果你想在所有的浏览器中都能正确使用 tag 标签，必须安装 pdf.js 依赖。
# 依赖：https://github.com/next-theme/theme-next-pdf
pdf:
  enable: true
  # 默认高度
  height: 800px
